### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by HannahDeWachter** [cultuurnet/search-v3#64]
Please make it compatible with PHP 8/8.1

**Comment by HannahDeWachter** [comment]
Hi @LucWollants , Is there news on this? We need this for the websites of "Jouw stad leest".

**Comment by LucWollants** [comment]
> Hi @LucWollants , Is there news on this? We need this for the websites of "Jouw stad leest".

Hi @HannahDeWachter, there are no plans to upgrade this to PHP 8.x

It would require a rather big rewrite and it seems better to adopt PHP 8.x features like `readonly` properties to clean up the code. If you are in for a pull request with an upgrade I am happy to review it!

**Comment by LucWollants** [comment]
> We are running the https://github.com/cultuurnet/search-v3/tree/epic/organizers branch on a PHP 8 server. There isn't a lot of differences with the main branch. So I would expect that main also is able to run on PHP 8.

Maybe it "runs", but the unit tests fail 😉

**Comment by zuuperman** [comment]
Yeah. Sorry for the wrong info. I checked the project. It is still running 7.4.

**Comment by LucWollants** [comment]
The main branch has support for PHP 8.2
